//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AampLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AampLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS
        ///Sword-Small
        ///Sword-Middle
        ///Sword-Large
        ///Sword-Huge
        ///LargeSword-Small
        ///LargeSword-Middle
        ///LargeSword-Large
        ///LargeSword-Huge
        ///Spear-Small
        ///Spear-Middle
        ///Spear-Large
        ///Spear-Huge
        ///Arrow-Small
        ///Arrow-Middle
        ///Arrow-Large
        ///Arrow-Huge
        ///Bomb-Small
        ///Bomb-Middle
        ///Bomb-Large
        ///Bomb-Huge
        ///Body-Small
        ///Body-Middle
        ///Body-Large
        ///Body-Huge
        ///Ancient-Small
        ///Ancient-Middle
        ///Ancient-Large
        ///Ancient-Huge
        ///ShockWave-Small
        ///ShockWave-Middle
        ///ShockWave-Large
        ///ShockWave-Huge
        ///Impulse-Small
        ///Impulse-Middle
        ///Impulse-Large
        ///Impulse-Huge
        ///GanonBeam-Small
        ///GanonBeam-Middle
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aamp_hashed_names {
            get {
                return ResourceManager.GetString("aamp_hashed_names", resourceCulture);
            }
        }
    }
}
